#!/usr/bin/env bash

fail() {
    echo $0
    exit 1
}
WHITELIST=\
"santyrojasprieto9+github@gmail.com santyrojasprieto9@gmail.com 95766532+santi100a@users.noreply.github.com"
# Get the author's email address
AUTHOR_EMAIL=$(git log -1 --format="%ae")

echo $WHITELIST | grep -q "$AUTHOR_EMAIL"
# Check if the author's email is in the whitelist
if [ $? -ne 1 ]; then
    echo "Author trusted: $AUTHOR_EMAIL, bypassing hook."
    exit 0
fi

npm --version
if ! npm ls --global | grep "yarn" > /dev/null; then
    npm i -g yarn@1.22.19
    echo "Yarn ready!"
else
    echo "Yarn found!"
fi

echo "📋 Validating package.json..."
yarn validate-package-json 
if [ $? -ne 0 ]; then
    fail "❌ Invalid package.json."
else
    echo "✅ package.json is valid."
fi
echo "✨ Running Prettier..."
yarn prettify
if [ $? -ne 0 ]; then
    fail "❌ Prettier error."
else
    echo "✅ Prettified successfully."
fi
echo "📦 Updating ESM wrapper..."
yarn esm-wrapper 
if [ $? -ne 0 ]; then
    fail "❌ An error occured."
else
    echo "✅ Wrapper updated successfully."
fi
echo "✅✅ Checks completed."